title: Finanzlabor.blog
subtitle: ''
description: >-
  Der Finanzlabor-Blog befasst sich mit den Themen Finanzen, Datenanalyse (Data
  Science) und Software-Programmierung und verpackt diese in lehrreiche
  Beiträge.
keywords: >-
  Finanzen, Aktien, Blog, Datenanalyse, Software, Programming, Data Mining, Data
  Science, Tutorials, Python, Aktienanalyse, Investoren, ETF, Open Data, DCF,
  P2P, Diagramme, GNUplot
author: Steve Aschwanden
language: de
timezone: Europe/Zurich
url: https://finanzlabor.blog
permalink: ':category/:post_title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: DD.MM.YYYY
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: ''
marked:
  prependRoot: true
  postAsset: true
feed:
  type: rss2
  path: rss2.xml
